CliKt integration
JetBrains/bunches pull request #37
Opened 2019-07-05 16:22 UTC by DmiitriyJarosh

2019-07-09 11:11 UTC, goodwinnk requested changes

2019-07-09 11:11 UTC, goodwinnk commented on bunch-cli/src/main/kotlin/org/jetbrains/bunches/check.kt
> +        process(config.getValue("VERBOSE"), ::doCheck.partial(settings))
It would be better to extract working with "VERBOSE" flag for all commands.

2019-07-09 11:11 UTC, goodwinnk commented on bunch-cli/src/main/kotlin/org/jetbrains/bunches/check.kt
> +        process(config.getValue("VERBOSE"), ::doCheck.partial(settings))
An explicit lambda can be used instead of declaring custom `partial` function: `process(config.getValue("VERBOSE")) { doCheck(settings) }` and the resulting code will be simpler.

2019-07-09 11:11 UTC, goodwinnk commented on bunch-cli/src/main/kotlin/org/jetbrains/bunches/check.kt
> +class CheckCommand : CliktCommand(name = "check", help = CHECK_DESCRIPTION, epilog = CHECK_EXAMPLE) {
Please apply reformat action to these blocks.

2019-07-09 11:11 UTC, goodwinnk commented on bunch-cli/src/main/kotlin/org/jetbrains/bunches/general.kt
> +    BunchCli().subcommands(commands).main(args)
Can `subcomands` be declared in `init` of `BunchCli`?

2019-07-09 11:11 UTC, goodwinnk commented on bunch-cli/src/main/kotlin/org/jetbrains/bunches/general.kt
> +//        "cp" -> cherryPick(commandArgs)
There were hidden items, can CliKt do the same?

2019-07-10 19:07 UTC, DmiitriyJarosh commented on bunch-cli/src/main/kotlin/org/jetbrains/bunches/general.kt
> +//        "cp" -> cherryPick(commandArgs)
Unfortunately, no

2019-07-29 14:31 UTC, Shasha33 commented on bunch-cli/src/main/kotlin/org/jetbrains/bunches/reduce.kt
> +
У меня при выводе игнорируются переносы строк. Что делать?)

2019-08-05 12:25 UTC, goodwinnk commented
Merged. Thank you!

2019-08-05 12:25 UTC, closed without merging